services:
  # Backend Service
  - type: web
    name: medicine-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT app:app
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medicine-tracker-db
          property: connectionString
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.7

  # Frontend Service
  - type: web
    name: medicine-tracker-ui
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: medicine-tracker-api
          type: web
          property: url

databases:
  - name: medicine-tracker-db
    plan: free
